steps:

#download the published pipelines artifact
- task: DownloadPipelineArtifact@2
  displayName: 'Infra - Download Artifact'
  inputs:
    artifact: 'infrastructure'
    path: $(System.ArtifactsDirectory)/infrastructure/

#deploy to azure
- task: AzureResourceGroupDeployment@2
  displayName: 'Infra - Deploy'
  inputs:
    azureSubscription: $ {{ parameters.spn }}
    action: 'Create Or Update Resource Group' # Options: create Or Update Resource Group, select Resource Group, start, stop, stopWithDeallocate, restart, delete, deleteRG
    resourceGroupName: "$(stage)-$(applicationName)-rg"
    csmFile: $(System.ArtifactsDirectory)/infrastructure/azuredeploy.json
    location: 'australiasoutheast'
    overrideParameters: -webAppName "$(stage)-$(applicationName)"